# Generated by Django 5.2.5 on 2025-08-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_tax_percentage_discount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
