# Generated by Django 5.2.5 on 2025-08-11 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_discount_order_alter_tax_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_percentage',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
