# Generated by Django 5.2.5 on 2025-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_discount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
    ]
